### PR TITLE
Add option to opt out of run time table creation

### PR DESCRIPTION
**Pull request by MrMDavidson**
When our application runs the connection provided to Rebus does not have schema modification rights. As such Rebus cannot dynamically create tables as needed. The other SQL Server implementations (eg. Saga) already have a similar option to not create tables at run time. Previously we would manually register the transport but there's a fair bit of logic inside the configuration extensions so we'd like to move away from this.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by MrMDavidson** [comment]
Note: think the test failures are related to the build environment? Running fine locally?

**Comment by mookid8000** [comment]
Could you try starting out with an empty database?

It seems to complain that tables are missing.

**Comment by MrMDavidson** [comment]
Hrm... I'll have to look into the unit tests for this more. I'm a little bit confused as to how this is happening from eyeballing it as the default is to opt in to table creation and only opt out when instructed. Might be worth while refactoring these extension methods to take an `Options` object to make code flow a bit clearer?

**Comment by MrMDavidson** [comment]
I tried running these into a two brand new database environments and, locally, they all passed using the Resharper test runner. Bit stumped as to what the issue could be here. Wondering if there's a test ordering issue? Or something to do with the one way client tests? 🤔 Any ideas?

image

**Comment by mookid8000** [comment]
Turned out that Appveyor was running tests in parallel for each compile target in the test project.

I solved it by setting up some compile-time constants, and then suffixing the database name with
```csharp
        static string CompileTargetSuffix
        {
            get
            {
                #if NET45
                return "net45";
                #elif NET46
                return "net46";
                #elif NETCOREAPP21
                return "netcoreapp21";
                #else
                throw new InvalidOperationException("please return suffix dependent on compile target");
                #endif
            }
        }
```

**Comment by mookid8000** [comment]
it's out in Rebus.SqlServer 6.0.0-a2 in a few minutes 🙂 

thanks! 👍

**Comment by MrMDavidson** [comment]
Yay! Thanks for the merges 😁

**Pull request merged**
