### PR TITLE
Update to rebus version 6

### PR DESCRIPTION
**Pull request by nativenolde**
@mookid8000 Hey mogens,

i tried to update the SQL Server transport library to rebus version 6… most of the work should be done.
Unfortunately there is no 'Rebus.Tests.Contracts' package version 6, which is required to complete the update.

Please feel free to pick up this PR and to update the package.

Sincerely,

nolde

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Is it necessary to update the Rebus dependency to v 6 ? 

(same question as on the Castle Windsor package 😁 )

**Comment by nativenolde** [comment]
Because of the changed namespaces in rebus version 6, the sql server transport does not work anymore.

System.AggregateException: One or more errors occurred.
Could not load type 'Rebus.Time.RebusTime' from assembly 'Rebus, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'.

--> System.TypeLoadException: Could not load type 'Rebus.Time.RebusTime' from assembly 'Rebus, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Rebus.SqlServer.Transport.SqlServerTransport.GetInitialVisibilityDelay(IDictionary`2 headers)
   at Rebus.SqlServer.Transport.SqlServerTransport.InnerSend(String destinationAddress, TransportMessage message, IDbConnection connection)
   at Rebus.SqlServer.Transport.SqlServerLeaseTransport.<>c__DisplayClass16_1.<<GetOutboundMessageBuffer>g__SendOutgoingMessages|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Rebus.Transport.TransactionContext.Invoke(ConcurrentQueue`1 actions)
   at Rebus.Transport.TransactionContext.RaiseCommitted()
   at Rebus.Transport.TransactionContext.Complete()
   at Rebus.Bus.RebusBus.InnerSend(IEnumerable`1 destinationAddresses, Message logicalMessage)
   at Rebus.Bus.RebusBus.Send(Object commandMessage, Dictionary`2 optionalHeaders)

**Comment by mookid8000** [comment]
ah okay, that's a good reason to update! 😁

**Comment by nativenolde** [comment]
> ah okay, that's a good reason to update! 😁

I fixed the changed namespaces and new dependencies with the best of my knowledge and certainty 😁

**Comment by mookid8000** [comment]
I think I've fixed what needed to be fixet 😄 thanks for pushing this, it's out in Rebus.SqlServer 6.0.0-a1

**Comment by nativenolde** [comment]
I'll deploy that into out testing environment and observe how it performs...

**Pull request merged**
