### PR TITLE
Saga serializer

### PR DESCRIPTION
**Pull request by mathiasnohall**
the actual use of the saga serializer configuration from rebus project

### CODE REVIEW

**Comment by mookid8000** [comment]
Cool cool 😃 if you move the `ISagaSerializer` thing here, you can easily let it default to a `DefaultSagaSerializer`, which will use Rebus' built-in `ObjectSerializer` to do its thing – then we're absolutely sure that the default behavior is preserved.

If you then add an extension method to `StandardConfigurer<ISagaStorage>` that will enable doing something like this:
```csharp
Configure.With(...)
	.(...)
	.Sagas(s => {
		s.StoreInSqlServer(...);
		s.UseSagaSerializer(new MyCustomSagaSerializer());
	})
	.Start();
```
then we've achieved what you're after, don't you think?

**Comment by mathiasnohall** [comment]
yes that makes sense :) I have moved the code now

**Comment by mookid8000** [comment]
Hi again @mathiasnohall , it's great that you've moved the serializer here... I can see that the build is failing though, because of a missing comment on `DefaultSagaSerializer`:
image

**Comment by mathiasnohall** [comment]
added comment :)

**Comment by mookid8000** [comment]
Excellent! It's out in Rebus.SqlServer 7.1.0 on NuGet.org in a few minutes 🙂 

Thanks for your contribution 👍

**Pull request merged**
