### PR TITLE
Create one table per input queue

### PR DESCRIPTION
**Pull request by magnus-tretton37**
Use input queue as the table (and ensure it exists) for receiving SQL queries and routing destination as the table for the sending SQL statement.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
BAM! Finally got around to merging this 😁 

It'll be out in Rebus.SqlServer version 5, which is out as a prerelease right now.... it would be awesome if someone would try this out and see if it's good (which I think it is!)

**Comment by mookid8000** [comment]
Awesome work btw – I am sure this is going to be good 🙂

**Comment by trevorreeves** [comment]
Can you give a brief description for why this change was needed?  It impacts on our deployment and configuration stories, so it would be great to have a justification to help prioritize the changes we will need to do to upgrade in the future.

**Comment by trevorreeves** [comment]
Great, thanks for the info.

**Pull request merged**
